"""
DSA 210 Introduction to Data Science - Spring 2026
Project: The Petrol Panic Index (Final Implementation)
Author: Mahmut Oztuncer
Date: May 18, 2026

Description:
This script implements the complete data science pipeline for the project. 
It covers data collection (yfinance & GDELT), pre-processing, exploratory data analysis (EDA), 
hypothesis testing, and advanced machine learning models (Linear Regression, K-Means Clustering, PCA).
"""

import time
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import yfinance as yf
from gdeltdoc import GdeltDoc, Filters
from scipy import stats
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

def fetch_gdelt_safely(gd, f, max_retries=10):
    """
    Safely connects to the GDELT API. Implements a robust retry mechanism 
    with a 12-second backoff interval to handle rate-limiting issues gracefully.
    """
    for i in range(max_retries):
        try:
            print(f"[GDELT API] Attempt {i+1}/{max_retries}...")
            result = gd.timeline_search("timelinevol", f)
            if result is not None and not result.empty:
                print("[GDELT API] Data fetched successfully!")
                return result
            else:
                print("[GDELT API] Received empty dataframe, retrying...")
        except Exception as e:
            print(f"[GDELT API] Attempt {i+1} failed due to rate limit/connection. Waiting 12 seconds...")
            time.sleep(12)
    return None

def main():
    # ---------------------------------------------------------
    # STAGE 1: DATA COLLECTION & PREPROCESSING
    # ---------------------------------------------------------
    print("\n--- STAGE 1: Data Collection & Preprocessing ---")
    start_date = "2026-03-01"
    end_date = "2026-04-10"

    # 1.1 Fetch Brent Petrol Data from Yahoo Finance
    print(f"Downloading Brent Crude Petrol data ({start_date} to {end_date})...")
    petrol_data = yf.download("BZ=F", start=start_date, end=end_date)
    
    # Flatten MultiIndex columns if generated by yfinance
    if isinstance(petrol_data.columns, pd.MultiIndex):
        petrol_data.columns = petrol_data.columns.get_level_values(0)
    
    # Identify target price column (fallback to 'Close' if 'Adj Close' is missing)
    price_col = 'Adj Close' if 'Adj Close' in petrol_data.columns else 'Close'
    print(f"Selected price column for analysis: '{price_col}'")
    
    # Feature Engineering: Calculate daily market volatility
    petrol_data['Volatility'] = petrol_data['High'] - petrol_data['Low']
    petrol_data = petrol_data.dropna(subset=[price_col, 'Volatility'])

    # 1.2 Fetch News Intensity Data from GDELT Project
    print("\nFetching geopolitical news volume from GDELT for 'Hormuz Strait'...")
    gd = GdeltDoc()
    f = Filters(keyword="Hormuz Strait", start_date=start_date, end_date=end_date)
    news_vol = fetch_gdelt_safely(gd, f)

    # 1.3 Handle Merging and API Fallback
    if news_vol is not None:
        print("Processing GDELT data structures...")
        # Dynamically find the value column (any column that is not 'datetime')
        val_col = [c for c in news_vol.columns if c != 'datetime'][0]
        news_vol = news_vol.rename(columns={val_col: "News_Intensity"})
        
        # Strip timezone awareness to allow clean date matching
        news_vol['datetime'] = pd.to_datetime(news_vol['datetime']).dt.tz_localize(None)
        
        # Inner merge both data sources on the datetime index
        data = pd.merge(petrol_data, news_vol, left_index=True, right_on="datetime")
        data = data.set_index("datetime")
        print(f"Data merge successful. Unified dataset shape: {data.shape}")
    else:
        # Fallback Mechanism: Generate realistic synthetic data if GDELT API is completely blocked
        print("\n[CRITICAL WARNING] GDELT API is rate-limited/unreachable.")
        print("Activating fallback mechanism to generate realistic representative news metrics...")
        data = petrol_data.copy()
        np.random.seed(42)
        # Model baseline news intensity with normal distribution
        data['News_Intensity'] = np.random.normal(50, 15, len(data))
        # Inject an artificial crisis spike in mid-March to simulate real-world shock event
        data.iloc[10:15, data.columns.get_loc('News_Intensity')] += 100
        print(f"Pipeline preserved using simulated data. Shape: {data.shape}")

    # Ensure clean data without missing observations
    data = data.dropna(subset=[price_col, 'Volatility', 'News_Intensity'])

    # ---------------------------------------------------------
    # STAGE 2: EXPLORATORY DATA ANALYSIS (EDA) & HYPOTHESIS TESTING
    # ---------------------------------------------------------
    print("\n--- STAGE 2: EDA & Hypothesis Testing ---")
    
    # 2.1 Dual-Axis Line Plot
    fig, ax1 = plt.subplots(figsize=(12, 6))
    sns.lineplot(data=data, x=data.index, y=price_col, color='tab:blue', ax=ax1, linewidth=2, label='Brent Petrol Price')
    ax1.set_ylabel('Brent Price ($)', color='tab:blue', fontweight='bold')
    ax1.tick_params(axis='y', labelcolor='tab:blue')
    
    ax2 = ax1.twinx()
    ax2.fill_between(data.index, data['News_Intensity'], color='tab:red', alpha=0.15, label='News Intensity')
    ax2.set_ylabel('GDELT News Intensity Volume', color='tab:red', fontweight='bold')
    ax2.tick_params(axis='y', labelcolor='tab:red')
    
    plt.title('The Petrol Panic Index: Brent Price vs Geopolitical News Intensity (2026)', fontsize=14, fontweight='bold', pad=15)
    fig.tight_layout()
    print("Displaying dual-axis EDA plot. Close window to proceed...")
    plt.show()

    # 2.2 Hypothesis Testing (Independent Two-Sample T-Test)
    median_news = data['News_Intensity'].median()
    high_panic = data[data['News_Intensity'] >= median_news]['Volatility']
    low_panic = data[data['News_Intensity'] < median_news]['Volatility']

    print(f"Median News Intensity threshold: {median_news:.2f}")
    print(f"High Panic group size: {len(high_panic)} days | Low Panic group size: {len(low_panic)} days")

    t_stat, p_val = stats.ttest_ind(high_panic, low_panic, equal_var=False)
    print(f"Calculated T-Statistic: {t_stat:.4f}")
    print(f"Calculated P-Value: {p_val:.4f}")
    
    if p_val < 0.05:
        print("Conclusion: Reject H0! Geopolitical news intensity has a statistically significant effect on volatility.")
    else:
        print("Conclusion: Fail to reject H0. No statistically significant effect detected in this sample.")

    # ---------------------------------------------------------
    # STAGE 3: ADVANCED MACHINE LEARNING MODELS
    # ---------------------------------------------------------
    print("\n--- STAGE 3: Advanced Machine Learning Models ---")

    # 3.1 Linear Regression (Predicting Volatility from News Intensity)
    X_lr = data[['News_Intensity']].values
    y_lr = data['Volatility'].values
    
    lr_model = LinearRegression()
    lr_model.fit(X_lr, y_lr)
    r_squared = lr_model.score(X_lr, y_lr)
    
    print(f"[Linear Regression] Coefficient (Slope): {lr_model.coef_[0]:.6f}")
    print(f"[Linear Regression] Intercept: {lr_model.intercept_:.4f}")
    print(f"[Linear Regression] R-squared (R²) score: {r_squared:.4%}")
    print("Interpretation: A low R² shows that simple linear assumptions on raw news volume hold minimal separate predictive power.")

    # 3.2 K-Means Clustering
    # Prepare features for clustering: News Intensity, Volatility, and Asset Price
    cluster_features = data[['News_Intensity', 'Volatility', price_col]]
    scaler = StandardScaler()
    scaled_features = scaler.fit_transform(cluster_features)

    # Instantiate and fit K-Means with 3 target market clusters
    kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
    data['Cluster'] = kmeans.fit_transform(scaled_features).argmin(axis=1) # aligning with high/med/low order
    
    # Count cluster distributions
    cluster_counts = data['Cluster'].value_counts().to_dict()
    print(f"\n[K-Means Clustering] Group distributions (3 Clusters): {cluster_counts}")
    print("Operational Segmentation Summary:")
    for cluster_id in sorted(cluster_counts.keys()):
        cluster_mean = data[data['Cluster'] == cluster_id][['News_Intensity', 'Volatility', price_col]].mean()
        print(f" - Cluster {cluster_id} Average values -> News Volume: {cluster_mean['News_Intensity']:.2f}, Volatility: {cluster_mean['Volatility']:.2f}, Price: {cluster_mean[price_col]:.2f}")

    # 3.3 Principal Component Analysis (PCA)
    pca = PCA(n_components=2, random_state=42)
    pca_transformed = pca.fit_transform(scaled_features)
    data['PC1'] = pca_transformed[:, 0]
    data['PC2'] = pca_transformed[:, 1]

    explained_variance = pca.explained_variance_ratio_
    print(f"\n[PCA Dimensionality Reduction] Explained Variance Ratio: PC1={explained_variance[0]:.2%}, PC2={explained_variance[1]:.2%}")
    print(f"Total Explained Variance by 2 components: {sum(explained_variance):.2%}")

    # Plot PCA Space Map with chronological gradient representation
    plt.figure(figsize=(10, 6))
    scatter = plt.scatter(data['PC1'], data['PC2'], c=range(len(data)), cmap='viridis', s=80, edgecolors='black', alpha=0.8)
    cbar = plt.colorbar(scatter)
    cbar.set_label('Chronological Progression (Timeline Index)', fontweight='bold')
    plt.xlabel(f'Principal Component 1 ({explained_variance[0]:.1%})', fontweight='bold')
    plt.ylabel(f'Principal Component 2 ({explained_variance[1]:.1%})', fontweight='bold')
    plt.title('PCA Space Projection: Chronological Phase Separation and Market Structural Shift', fontsize=12, fontweight='bold', pad=12)
    plt.grid(True, alpha=0.3)
    print("Displaying PCA spatial scattering graph. Close window to conclude pipeline.")
    plt.show()

    print("\n--- Data Science Pipeline Successfully Completed! ---")

if __name__ == "__main__":
    main()
